### ISSUE TITLE
Add a  function that will encapsulate the creation of the user when creating the player.

### ISSUE THREAD

**Issue by Danielsio** [redhat-beyond/MeetBalls#36]

**Comment by Danielsio** [comment]
if I add a create_user method that will return user instance similar to the user_fixture

and i will add it ti the player/models

would that count as a solution for this issue ?

i mean something like this: 

class Player(models.Model):
  ... class fields...
  
def create_default_user():
    return get_user_model().objects.create_user(
        username='testuser',
        password='password')
        
and player creation will look like this:
from player.models import create_default_user
 @pytest.fixture
def player():
    player = Player.objects.create(
        user=create_default_user(),
        birth_date='1990-01-01',
        favorite_ball_game=BallGame.Soccer)
    return player

**Comment by yftacherzog** [comment]
I think you might want to go with overriding the `save` method or something like that. Similar to what @ZvikaNaorCohen did with the court.
