### ISSUE TITLE
Add template for a login page

### ISSUE THREAD

**Issue by OhadSeg** [redhat-beyond/MeetBalls#74]
## Expected Behavior

users will have a template of a login page.

## Current Behavior
There is currently no template for it 

### Acceptance Criteria

1. Login page template should be added
2. Relevant routing for the template should be added
3. Small adjustments in the base.html should be done.
4. Relevant tests for the login mechanism should be added

**Comment by Danielsio** [comment]
I will close this manually since #75 got merged.
